import type { IColumn } from '../../shared/types/database';
import type { IDatabaseAdapter } from '../database/interfaces/IAdapter';

export interface MockDataOptions {
  rowCount: number;
  columnOverrides?: Record<string, string>;
}

const FIRST_NAMES = ['James', 'Mary', 'Robert', 'Patricia', 'John', 'Jennifer', 'Michael', 'Linda', 'David', 'Elizabeth', 'William', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen'];
const LAST_NAMES = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin'];
const DOMAINS = ['example.com', 'test.org', 'demo.net', 'mail.com', 'company.io'];
const STATUSES = ['active', 'inactive', 'pending', 'archived', 'draft'];
const CITIES = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'];
const LOREM = 'Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua'.split(' ');

export class MockDataService {
  generateRows(columns: IColumn[], options: MockDataOptions): Record<string, unknown>[] {
    const rows: Record<string, unknown>[] = [];

    for (let i = 0; i < options.rowCount; i++) {
      const row: Record<string, unknown> = {};

      for (const col of columns) {
        if (col.autoIncrement || (col.primaryKey && this.isAutoGenerated(col))) {
          continue;
        }

        const override = options.columnOverrides?.[col.name];
        if (override) {
          row[col.name] = this.generateByPattern(override, i);
        } else {
          row[col.name] = this.generateValue(col, i);
        }
      }

      rows.push(row);
    }

    return rows;
  }

  async generateAndInsert(
    adapter: IDatabaseAdapter,
    table: string,
    columns: IColumn[],
    options: MockDataOptions
  ): Promise<{ inserted: number; errors: number }> {
    const rows = this.generateRows(columns, options);
    let inserted = 0;
    let errors = 0;

    for (const row of rows) {
      try {
        await adapter.insertRow(table, row);
        inserted++;
      } catch {
        errors++;
      }
    }

    return { inserted, errors };
  }

  private isAutoGenerated(col: IColumn): boolean {
    const type = col.type.toUpperCase();
    return type.includes('SERIAL') || type.includes('AUTO_INCREMENT') || col.autoIncrement === true;
  }

  private generateValue(col: IColumn, index: number): unknown {
    const name = col.name.toLowerCase();
    const type = col.type.toUpperCase();

    // Name-based inference
    if (name.includes('email')) return this.randomEmail(index);
    if (name === 'first_name' || name === 'firstname') return this.randomPick(FIRST_NAMES);
    if (name === 'last_name' || name === 'lastname') return this.randomPick(LAST_NAMES);
    if (name === 'name' || name === 'full_name' || name === 'fullname') return `${this.randomPick(FIRST_NAMES)} ${this.randomPick(LAST_NAMES)}`;
    if (name.includes('phone') || name.includes('tel')) return this.randomPhone();
    if (name.includes('address') || name.includes('street')) return `${this.randomInt(1, 9999)} ${this.randomPick(LAST_NAMES)} St`;
    if (name.includes('city')) return this.randomPick(CITIES);
    if (name.includes('zip') || name.includes('postal')) return String(this.randomInt(10000, 99999));
    if (name.includes('country')) return 'US';
    if (name.includes('url') || name.includes('website') || name.includes('link')) return `https://example.com/${this.randomString(8)}`;
    if (name.includes('status')) return this.randomPick(STATUSES);
    if (name.includes('description') || name.includes('text') || name.includes('body') || name.includes('content')) return this.randomText(10, 20);
    if (name.includes('title') || name.includes('subject')) return this.randomText(3, 6);
    if (name.includes('price') || name.includes('amount') || name.includes('cost') || name.includes('total')) return this.randomDecimal(1, 999, 2);
    if (name.includes('quantity') || name.includes('count') || name.includes('num')) return this.randomInt(1, 100);
    if (name.includes('age')) return this.randomInt(18, 80);
    if (name.includes('rating') || name.includes('score')) return this.randomDecimal(1, 5, 1);
    if ((name.includes('is_') || name.includes('has_') || name.includes('can_')) || type === 'BOOLEAN' || type === 'BOOL') return Math.random() > 0.5;
    if (name.includes('created') || name.includes('updated') || name.includes('date') || name.includes('_at')) return this.randomDate();
    if (name.includes('uuid') || name.includes('guid')) return this.randomUUID();

    // Type-based inference
    if (type.includes('INT') || type.includes('SERIAL')) return this.randomInt(1, 10000);
    if (type.includes('FLOAT') || type.includes('DOUBLE') || type.includes('REAL') || type.includes('DECIMAL') || type.includes('NUMERIC')) return this.randomDecimal(0, 1000, 2);
    if (type.includes('BOOL')) return Math.random() > 0.5;
    if (type.includes('DATE') || type.includes('TIME') || type.includes('TIMESTAMP')) return this.randomDate();
    if (type.includes('JSON')) return JSON.stringify({ key: `value_${index}` });
    if (type.includes('UUID')) return this.randomUUID();
    if (type.includes('TEXT') || type.includes('CLOB')) return this.randomText(10, 30);

    // Default: random string
    return this.randomString(10);
  }

  private generateByPattern(pattern: string, index: number): unknown {
    switch (pattern) {
      case 'email': return this.randomEmail(index);
      case 'name': return `${this.randomPick(FIRST_NAMES)} ${this.randomPick(LAST_NAMES)}`;
      case 'phone': return this.randomPhone();
      case 'date': return this.randomDate();
      case 'int': return this.randomInt(1, 10000);
      case 'float': return this.randomDecimal(0, 1000, 2);
      case 'bool': return Math.random() > 0.5;
      case 'uuid': return this.randomUUID();
      case 'text': return this.randomText(10, 20);
      case 'status': return this.randomPick(STATUSES);
      case 'city': return this.randomPick(CITIES);
      default: return pattern;
    }
  }

  private randomEmail(seed: number): string {
    const first = this.randomPick(FIRST_NAMES).toLowerCase();
    const last = this.randomPick(LAST_NAMES).toLowerCase();
    return `${first}.${last}${seed}@${this.randomPick(DOMAINS)}`;
  }

  private randomPhone(): string {
    return `+1${this.randomInt(200, 999)}${this.randomInt(100, 999)}${this.randomInt(1000, 9999)}`;
  }

  private randomDate(): string {
    const start = new Date(2020, 0, 1).getTime();
    const end = new Date().getTime();
    const date = new Date(start + Math.random() * (end - start));
    return date.toISOString().slice(0, 19).replace('T', ' ');
  }

  private randomText(minWords: number, maxWords: number): string {
    const count = this.randomInt(minWords, maxWords);
    const words: string[] = [];
    for (let i = 0; i < count; i++) {
      words.push(this.randomPick(LOREM));
    }
    const text = words.join(' ');
    return text.charAt(0).toUpperCase() + text.slice(1);
  }

  private randomString(length: number): string {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }

  private randomUUID(): string {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = Math.random() * 16 | 0;
      const v = c === 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }

  private randomInt(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  private randomDecimal(min: number, max: number, decimals: number): number {
    return Number((Math.random() * (max - min) + min).toFixed(decimals));
  }

  private randomPick<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
  }
}
